### ISSUE TITLE
About multi-GPU training

### ISSUE THREAD

**Issue by dingmyu** [garrickbrazil/M3D-RPN#10]
Hi, is your model trained with a single GPU? Have you tried using multiple GPUs?
I encountered the following error when using data-parallel in multi-GPU training.

  File "scripts/train_rpn_3d.py", line 122, in main
    cls, prob, bbox_2d, bbox_3d, feat_size = rpn_net(images)
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/mnt/lustre/dingmingyu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

Do you know how to fix this? And I would like to ask about single (batch_size = 2) and multi-GPU (larger batch_size, e.g. 16) training, which one would have better performance? Thank you very much!

**Comment by dingmyu** [comment]
I also wonder why using different split consumes different GPU memory, since the image size and batch size are the same. The reason is the number of images is different? Thank you.

**Comment by brazgardian** [comment]
In the current moment, I do not have free GPU's to test out the multi-gpu error. However, if you determine a solution please feel encouraged to post it here. I assume it has to do with the method we collate the batch which was only tested on a single GPU. As a simple check, you can try changing line 289 in imdb_util.py to "return imgs, np.array(imobjs)". This is just a guess though since I do not have a free GPUs to look into it this second.

Regarding whether larger batch sizes will help performance, I am not sure. However, it will likely get more stable results and train quicker if a larger learning rate is also used.

Lastly, what is the GPU memory difference between split1 and split2? If it is reasonable than it is probably due to small changes in the aspect ratio (e.g., width since height is fixed) of images between the splits. When pytorch allocates the memory it seems to keep it rather than constantly releasing and re-allocating, which means the memory we see used is likely the maximum memory needed so far (to my understanding).

**Comment by dingmyu** [comment]
Thank you for your quick reply! I will try multi-GPU training, if there is a solution, I will post it here. 

|   0  TITAN Xp            On   | 00000000:04:00.0 Off |                  N/A |
| 43%   68C    P2    86W / 250W |   6673MiB / 12189MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            On   | 00000000:05:00.0 Off |                  N/A |
| 41%   67C    P2    89W / 250W |  11907MiB / 12189MiB |      2%      Default

This model can be perfectly trained under the kitti_split1. The memory change means that when I changed the datasets_train[{'name'}] in config file from kitti_split1 to kitti (Only this one modification), the memory consumption was changed from 7G to 12G. And the iou/cls during training became NAN, the fg acc was always 0 as follows. Why can't I use the full raw dataset to train the model? 

iter: 250, acc (bg: 0.97, fg: 0.02, iou: nan), loss (bbox_3d: inf, cls: nan, iou: nan), misc (ry: inf, z: inf), dt: 0.67, eta: 9.2h
iter: 500, acc (bg: 1.00, fg: 0.00, iou: nan), loss (bbox_3d: inf, cls: nan, iou: nan), misc (ry: inf, z: inf), dt: 0.64, eta: 8.8h

Is there any problem with this modification? I want to train the full Kitti dataset and test it with the testing set, so I can submit the results to the Kitti website.

**Comment by yourlovedu** [comment]
I think I've found what the problem is about 'TypeError: zip argument #1 must support iteration' for multi-gpu training.
It is because that the type of one ouput called 'feat_size' of the net is list. To solve the problem, just adding the following code after 'feat_size = [feat_h, feat_w]' in 'forward' in the model files: 
feat_size = torch.tensor(feat_size)
or just change 'feat_size = [feat_h, feat_w]' to 'feat_size = torch.tensor([feat_h, feat_w])' .
Don't forget to change the conf.batch_size in config files to batchs_per_gpu*number_of_gpu.
And I think the iteration and learning rate should also be adjusted.

**Comment by brazgardian** [comment]
@yourlovedu  Great observation! And nice of you to post it here for others.
